### ISSUE TITLE
PHP not installed

### ISSUE THREAD

**Issue by ressof** [Dashticz/dashticz#1062]
Hi 
Im running Dashticz on an Alpine linux with nginx and PHP8.1. But when I load dashticz it says that PHP is not installed. But other installations that use PHP works. Is there anything special I need to config in nginx or is php8.1 not supported?

**Comment by lokonli** [comment]
What is the php version as reported in Dashticz?
(settings icon upper right, then info tab)

I did not test on Alpine linux. Maybe you have to install some additional php modules to integrate with nginx.
I'll try to reproduce.

**Comment by ressof** [comment]
It says that PHP is not installed

**Comment by lokonli** [comment]
ok. Did some experiments my self.

If you are running Alpine Linux within a docker container instructions will be different!
(because the Docker container will use a read-only file system)

On your Alpine Linux start a shell as root.

Create a file /tmp/dashticz_alpine_nginx.conf with the following content:
```
server {
        listen 8080;
        listen [::]:8080;
        root /etc/nginx/html/dashticz;
        index index.html;
}
```

Then execute the following script:
```
# Execute this script as root on a clean alpine install
apk update
apk upgrade
apk add git nginx php81 php81-fpm php81-opcache php81-curl nano
cd /etc/nginx
mkdir html
cd html
git clone https://github.com/Dashticz/dashticz --branch beta
cp /tmp/dashticz_alpine_nginx.conf /etc/nginx/http.d
rc-update add nginx default
rc-update add php-fpm81 default
rc-service nginx restart
rc-service php-fpm81 restart
```

Then configure Dashticz:
```
cp /etc/nginx/html/dashticz/custom/CONFIG_DEFAULT.js /etc/nginx/html/dashticz/custom/CONFIG.js
```

Edit CONFIG.js and change domoticz ip to your actual server running Domoticz:
```
nano /etc/nginx/html/dashticz/custom/CONFIG.js
```

Then you should have a working version of nginx+php.

**Comment by ressof** [comment]
Hi

Thank you for your help. But this still does not work :(

**Comment by lokonli** [comment]
What is the error message that you get?

http://dashticz ip:port/vendor/dashticz/info.php?get=phpversion

**Comment by ressof** [comment]
It just download info.php when I access that page
