### ISSUE TITLE
OMW 3.0 not working

### ISSUE THREAD

**Issue by MadPatrick** [Dashticz/dashticz#1203]
Hi
I've upgrade to OMW 3.0, but now this is not working anymore in Dashticz

I'm getting 
[code]Error : owm3 error. No valid API key[/code]

Created a new key:
[code]Error: No valid API key? (Autodetect provider)[/code]

What can this be?

See post : https://www.domoticz.com/forum/viewtopic.php?p=320967#p320967

**Comment by TroisSix** [comment]
@MadPatrick, 

I hope you found the good parameters since the end of october :/

On my side, I have validated the subscription with 1000 free calls per day, and I use the following parameters:
[code]
config['provider'] ='owm3'; // with or without it works the same
config['owm_api'] ='XXXX'; // only the key id of your account
config['owm_city'] = 'My City'; // with the id it is not working
config['owm_name'] = 'My City'; // the name to display
config['owm_country'] = 'fr';
config['owm_lang'] = 'fr'; // doesn't seem to work :-(
[/code]

Hope it will helps some or others :-)

**Comment by MadPatrick** [comment]
Hi TroiSIx
Still not working
I've a valid OMW3 subscription.
Tested it with https://api.openweathermap.org/data/3.0/onecall?lat=33.44&lon=-94.04&exclude=hourly,daily&appid=[APIKEY]

still not working within Dashticz

**Comment by MadPatrick** [comment]
I've it working now

added this in the bloks

[code]	apikey: 'key',
	provider: 'owm3',[/code]

and changed owm_city from city number to city name
[code]
config['owm_city'] = 'cityname';[/code]
